USE [master]
GO

/****** Object:  Database [Document]    Script Date: 05/14/2013 15:02:32 ******/
CREATE DATABASE [Document] ON  PRIMARY 
( NAME = N'Document', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Document.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Document_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\Document_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Document] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Document].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Document] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Document] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Document] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Document] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Document] SET ARITHABORT OFF 
GO

ALTER DATABASE [Document] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Document] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Document] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Document] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Document] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Document] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Document] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Document] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Document] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Document] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Document] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Document] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Document] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Document] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Document] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Document] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Document] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Document] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Document] SET  READ_WRITE 
GO

ALTER DATABASE [Document] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Document] SET  MULTI_USER 
GO

ALTER DATABASE [Document] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Document] SET DB_CHAINING OFF 
GO


/****** Object:  Table [dbo].[DocumentStore]    Script Date: 05/14/2013 15:05:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[DocumentStore](
	[_id] [uniqueidentifier] NOT NULL,
	[document] [nvarchar](max) NOT NULL,
	[type] [varchar](50) NOT NULL,
	[internalId] [int] NOT NULL,
 CONSTRAINT [PK_DocumentStore] PRIMARY KEY CLUSTERED 
(
	[_id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

